### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.asyncIterator)' of undefined

### ISSUE THREAD

**Issue by heineiuo** [splashdb/client#2]
```
TypeError: Cannot read property 'Symbol(Symbol.asyncIterator)' of undefined
    at Function.read (/index.js:224:32)
    at read.next (<anonymous>)
    at s (/index.js:976:22)
    at a.tableIterator (/index.js:996:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async a.find (/index.js:1175:24)
    at async TokenManager.query (/index.js:1430:23)
    at async resolve (/index.js:2178:20)
```

```js
  async function s(r) {
    const e = {};

    for await (const n of build.BootBuffer.read(r)) e[n.key] = n.value;

    return e;
  }

```

**Comment by heineiuo** [comment]
`ServerHttp2Stream` buffer the write data, so client may not receive a complete BootBuffer format stream response. Client should cache stream data.
